twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello microservice!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  max-attempts: 3
  multiplier: 2.0
  sleep-time-ms: 2000


kafka-config:
  bootstrap-servers: localhost:19091 localhost:19092 localhost:19093
  schema-registry-url: http://localhost:8081
  schema-registry-key: schema.registry.url
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  number-of-partitions: 3
  replication-factor: 3
